import type { Metadata } from "next";
import "./globals.css";
import { sen } from "./lib/fonts";

export const metadata: Metadata = {
  title: "H",
  description: "Generated by MountainSoft",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sen.className}>{children}</body>
    </html>
  );
}
